server:
  port: 9527
spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_route1  # 路由的 ID，没有固定规则但要求唯一
#          uri: http://localhost:8081 #匹配后服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由

        - id: payment_route2
#          uri: http://localhost:8081
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

